# Train cityscapes with deeplab v3+ and wide-resnet-38 trunk
# Only requires 16GB gpus

CMD: "python -m torch.distributed.launch --nproc_per_node=1 train.py"

HPARAMS: [
  {
   dataset: cityscapes,
   cv: 0,
   syncbn: true,
   apex: true,
   fp16: true,
   crop_size: "1024,2048",
   bs_trn: 2,
   poly_exp: 2,
   lr: 5e-3,
   max_epoch: 175,
   arch: deepv3.DeepV3PlusW38,
   result_dir: LOGDIR,
   RUNX.TAG: '{arch}',
   snapshot: "/home/zcy/lyj/semantic-segmentation-main/logs/train_cityscapes_deepv3_new/deepv3.DeepV3PlusW38_wild-mouflon_2023.05.16_09.35/last_checkpoint_ep9.pth",
  },
]
